### ISSUE TITLE
app-forensics/checksec is now app-admin/checksec in Gentoo

### ISSUE THREAD

**Issue by hartwork** [no-hope/fw-overlay#3]
Hi!

You can resolve `app-forensics/checksec-1.4` now if you like. Version 1.7.2 is now `app-admin/checksec` in Gentoo, see https://github.com/gentoo/gentoo/commit/bc5a59eb44d1bdc7186dfca7a32758c9d50b5caa.

Best, Sebastian

**Comment by pshirshov** [comment]
Thanks a lot, we will remove our ebuild.

**Comment by pshirshov** [comment]
7b82747

**Comment by hartwork** [comment]
That was quick :) Thank you!
